// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfgHXSn8rDqRDGj0QCs4ISf9ud8RTWNcE',
    appId: '1:757639821628:web:70db87a69347ae140d8639',
    messagingSenderId: '757639821628',
    projectId: 'heforher-15a4a',
    authDomain: 'heforher-15a4a.firebaseapp.com',
    storageBucket: 'heforher-15a4a.firebasestorage.app',
    measurementId: 'G-GZGWWR4H4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAazj5nzALywSSw6QGBwH8L8bBJIRDaT7s',
    appId: '1:757639821628:android:94adf950f359bf010d8639',
    messagingSenderId: '757639821628',
    projectId: 'heforher-15a4a',
    storageBucket: 'heforher-15a4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGdakXY_SCWQodOeHMYPQFy54ZPAEADgc',
    appId: '1:757639821628:ios:7733177f4a89a9940d8639',
    messagingSenderId: '757639821628',
    projectId: 'heforher-15a4a',
    storageBucket: 'heforher-15a4a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGdakXY_SCWQodOeHMYPQFy54ZPAEADgc',
    appId: '1:757639821628:ios:7733177f4a89a9940d8639',
    messagingSenderId: '757639821628',
    projectId: 'heforher-15a4a',
    storageBucket: 'heforher-15a4a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfgHXSn8rDqRDGj0QCs4ISf9ud8RTWNcE',
    appId: '1:757639821628:web:dc2dda018a90561b0d8639',
    messagingSenderId: '757639821628',
    projectId: 'heforher-15a4a',
    authDomain: 'heforher-15a4a.firebaseapp.com',
    storageBucket: 'heforher-15a4a.firebasestorage.app',
    measurementId: 'G-MYL046P69V',
  );
}
